### ISSUE TITLE
Importar Textura JPG ou PNG

### ISSUE THREAD

**Issue by Kanime10** [light-tracer/issues#2]
Hello, how are you?

My name is Keiton and I have one question:

It is possible to import textures, I could not find.

Tks.
Keiton

**Comment by denisbogol** [comment]
Hi Keiton,

Textures are planned, but, unfortunately, will not be available very soon. We hope to add texture support in the next 2 months.

BR,
Denis

**Comment by Kanime10** [comment]
Hi Denisbogol,

Many thanks for the reply.
I am anxiously waiting :)

tks,
Keiton

**Comment by denisbogol** [comment]
Hi @Kanime10 ,

We have released beta (unstable!) LightTracer with support of textures and metalness workflow:
https://lighttracer.org/1.0.0-b2/

It will be available officially after QA and testing. If you want, you may try it now. Any feedback and bug reports would be very useful!

**Comment by hb3p8** [comment]
Textures are now available in public version of LightTracer.

**Comment by Kanime10** [comment]
Inglês
Olá Muito obrigado!

Excelente! Cada vez melhor, espero ver outras atualizações em breve, não deixem de me avisar por favor.

Saudações
Keiton :)
  Aprenda a pronunciar
Hello thank you so much!

Great! Better and better, I hope to see other updates soon, please let me know.

greetings
Keiton :)
