### ISSUE TITLE
Gallery: Post your renders here

### ISSUE THREAD

**Issue by hb3p8** [light-tracer/issues#4]
Feel free to post your renders here!
![image](https://user-images.githubusercontent.com/1812916/60019146-e5ba5c00-9695-11e9-8b33-996425ec0154.png)

**Comment by hb3p8** [comment]
Renders by @ArixCuriax
![59975334-ec769f80-95bf-11e9-9f38-51762f818b45](https://user-images.githubusercontent.com/1812916/60091374-18735b80-974d-11e9-8f73-9eb6d59ce8c3.png)
![59980612-d63d0380-9600-11e9-8f1a-9f1c5cb30cb0](https://user-images.githubusercontent.com/1812916/60091377-1ad5b580-974d-11e9-956a-684d4a198a2f.png)

**Comment by hb3p8** [comment]
Render by @rukibuki
![59980520-6a09d200-95f7-11e9-87d1-7a4cad35d4e1](https://user-images.githubusercontent.com/1812916/60091495-62f4d800-974d-11e9-92d1-3af3c23d609b.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/60092124-e3680880-974e-11e9-9a71-709da8540c05.png)
![image (6)](https://user-images.githubusercontent.com/52126951/60092126-e3680880-974e-11e9-9bf9-3bd21cdbe20b.png)
![image (5)](https://user-images.githubusercontent.com/52126951/60092127-e3680880-974e-11e9-9383-803d652b45e5.png)
![image (1)](https://user-images.githubusercontent.com/52126951/60092129-e4009f00-974e-11e9-9fe0-fee8907a0e4a.png)
![image (1) (1)](https://user-images.githubusercontent.com/52126951/60092130-e4009f00-974e-11e9-92d1-1a800f723f0c.png)
![image (1) (2)](https://user-images.githubusercontent.com/52126951/60092131-e4009f00-974e-11e9-8f58-e671260dad23.png)
![image (2)](https://user-images.githubusercontent.com/52126951/60092132-e4009f00-974e-11e9-8ca0-914684f436f7.png)
![image (4)](https://user-images.githubusercontent.com/52126951/60092133-e4993580-974e-11e9-9c15-dcc23f485ec0.png)
![image 2](https://user-images.githubusercontent.com/52126951/60092135-e4993580-974e-11e9-8a14-0fbd40aeb9d9.png)
![image (7)](https://user-images.githubusercontent.com/52126951/60092136-e531cc00-974e-11e9-9510-17432ba44272.png)
![image (8)](https://user-images.githubusercontent.com/52126951/60092137-e531cc00-974e-11e9-83f2-1f5afdc27aaa.png)

**Comment by ArixCuirax** [comment]
![image (1)](https://user-images.githubusercontent.com/52126951/60097755-bcb0ce80-975c-11e9-8fee-da8d8251e4f3.png)
![image](https://user-images.githubusercontent.com/52126951/60097756-bcb0ce80-975c-11e9-9c3e-942aa83734d2.png)

**Comment by ArixCuirax** [comment]
Thank you for providing this awesome renderer for free, for anyone to use. Without it, I would not have had any way to produce good looking renders of my models except perhaps learn how to use Blender. Or buy an expensive software like Keyshot or others.

![image](https://user-images.githubusercontent.com/52126951/60124644-c5bc9280-9792-11e9-9786-1debcd3e7e5b.png)

**Comment by denisbogol** [comment]
Hi @ArixCuirax,

Thanks a lot for amazing renders! And stay posted for more features coming soon.

**Comment by ArixCuirax** [comment]
Thank you for this awesome software!

![image](https://user-images.githubusercontent.com/52126951/60129805-8431e480-979e-11e9-88e3-e44e18f6f2ff.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/60141055-860aa080-97bc-11e9-864a-916ee6be1d4d.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/60200349-9cf9d300-984e-11e9-93a9-b69578769e86.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/60200682-3d4ff780-984f-11e9-8744-6ac0fb7c9b0c.png)

**Comment by hb3p8** [comment]
![image (6)](https://user-images.githubusercontent.com/1812916/60209784-0506e400-9864-11e9-98f7-dff4803bc5da.png)
Models from:
https://www.thingiverse.com/thing:3704460
https://pinshape.com/items/34132-3d-printed-avengers-scene-the-incredible-hulk-3d-model-for-printing

**Comment by hb3p8** [comment]
![image](https://user-images.githubusercontent.com/1812916/60210755-4f896000-9866-11e9-9189-cadd1a4a33f4.png)
Model from:
https://pinshape.com/items/6334-3d-printed-elephant-voronoi-style

**Comment by hb3p8** [comment]
![minis](https://user-images.githubusercontent.com/1812916/60292492-e9fca880-9925-11e9-80ba-24f591dd02d7.png)
Sample models from https://www.heroforge.com/

**Comment by ArixCuirax** [comment]
![image(1)](https://user-images.githubusercontent.com/52126951/60403327-5a186200-9ba4-11e9-86c6-2ce456c26f5a.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/60521709-67426780-9cf0-11e9-9365-6ddba47cad29.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/60521855-9fe24100-9cf0-11e9-8cfe-a91362fd1564.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/60625822-95f43700-9df1-11e9-84e8-775ccf640ba6.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/61296929-ca012c00-a7e3-11e9-8fd1-024f9de956a0.png)
![image (1)](https://user-images.githubusercontent.com/52126951/61296966-e3a27380-a7e3-11e9-80ad-26ad6779af88.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/61578116-5704f780-aafa-11e9-8c7b-450d55364ea1.png)
![image (1)](https://user-images.githubusercontent.com/52126951/61578117-58362480-aafa-11e9-9cee-45a239c0203b.png)
I think I should have used a higher resolution HDRi for the second render.

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/61591357-d401a100-abce-11e9-9c15-eff22dcdceb1.png)
![image](https://user-images.githubusercontent.com/52126951/61591360-d9f78200-abce-11e9-9f9d-912817132c5f.png)
![image](https://user-images.githubusercontent.com/52126951/61591373-e8de3480-abce-11e9-9d1c-2676582a00fe.png)
![image](https://user-images.githubusercontent.com/52126951/61591377-ed0a5200-abce-11e9-8368-d7d8f9d98d5f.png)

**Comment by ArixCuirax** [comment]
![image (3) (1)](https://user-images.githubusercontent.com/52126951/62089941-a0c8ad00-b273-11e9-80e1-5c9550999869.png)
![image (1) (1)](https://user-images.githubusercontent.com/52126951/62089942-a0c8ad00-b273-11e9-8ba3-d2af2b807cd8.png)
![image (2) (1)](https://user-images.githubusercontent.com/52126951/62089943-a0c8ad00-b273-11e9-8170-9dbd95d96463.png)
![image (4)](https://user-images.githubusercontent.com/52126951/62089944-a0c8ad00-b273-11e9-8482-3e1352d9dab9.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/62113562-82879f00-b2bd-11e9-9f41-ccc628d57b1f.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/63082883-101aee00-bf50-11e9-8e1e-f9e94a7cfaab.png)
![image](https://user-images.githubusercontent.com/52126951/63082923-22952780-bf50-11e9-8f35-07fc10d797e3.png)
![image](https://user-images.githubusercontent.com/52126951/63082953-32147080-bf50-11e9-8549-8aceb2636723.png)

**Comment by ArixCuirax** [comment]
![image (6)](https://user-images.githubusercontent.com/52126951/68994052-07a3bd80-0887-11ea-8135-76f210139a7b.png)
![image (5)](https://user-images.githubusercontent.com/52126951/68994053-07a3bd80-0887-11ea-90d0-a9474496e459.png)

**Comment by ArixCuirax** [comment]
![image (5)](https://user-images.githubusercontent.com/52126951/69058380-399a5880-0a1c-11ea-9f57-f19190ea0007.png)
![image (6)](https://user-images.githubusercontent.com/52126951/69058382-399a5880-0a1c-11ea-97d6-7da9e3d76e8e.png)
![image (7)](https://user-images.githubusercontent.com/52126951/69058384-3a32ef00-0a1c-11ea-9215-1caa3b0a9583.png)
![image (8)](https://user-images.githubusercontent.com/52126951/69058385-3a32ef00-0a1c-11ea-8c3d-ab44fb0f49e9.png)

**Comment by ArixCuirax** [comment]
![image (5)](https://user-images.githubusercontent.com/52126951/69243704-48177a00-0bac-11ea-8536-d52939692354.png)
![image (6)](https://user-images.githubusercontent.com/52126951/69243706-48177a00-0bac-11ea-89c8-29df38c63294.png)
![image (7)](https://user-images.githubusercontent.com/52126951/69243707-48b01080-0bac-11ea-820f-4963ef3841d1.png)
![image (8)](https://user-images.githubusercontent.com/52126951/69243708-48b01080-0bac-11ea-8593-839fe41c4087.png)
![image (9)](https://user-images.githubusercontent.com/52126951/69243709-48b01080-0bac-11ea-8389-08444268e914.png)
![image (10)](https://user-images.githubusercontent.com/52126951/69243712-4948a700-0bac-11ea-8fc0-9e2e7474a196.png)

**Comment by ArixCuirax** [comment]
![image (14)](https://user-images.githubusercontent.com/52126951/69243812-79904580-0bac-11ea-9c74-fe95d8db1fd8.png)
![image (12)](https://user-images.githubusercontent.com/52126951/69243814-79904580-0bac-11ea-9344-6405d27233a4.png)
![image (20)](https://user-images.githubusercontent.com/52126951/69243816-7a28dc00-0bac-11ea-9792-d277a5f8b0c5.png)
![image (16)](https://user-images.githubusercontent.com/52126951/69243817-7a28dc00-0bac-11ea-9aaa-8fcea8aaa2f4.png)
![image (18)](https://user-images.githubusercontent.com/52126951/69243819-7a28dc00-0bac-11ea-9f08-32eeb77d8f14.png)
![image (19)](https://user-images.githubusercontent.com/52126951/69243821-7a28dc00-0bac-11ea-9a11-d56319a279aa.png)
![image (17)](https://user-images.githubusercontent.com/52126951/69243822-7ac17280-0bac-11ea-9005-9c60863d9398.png)
![image (13)](https://user-images.githubusercontent.com/52126951/69243823-7ac17280-0bac-11ea-8a6f-1f778401cc8c.png)
![image (15)](https://user-images.githubusercontent.com/52126951/69243844-857c0780-0bac-11ea-8a5b-65b96c82ac20.png)

**Comment by ArixCuirax** [comment]
![image](https://user-images.githubusercontent.com/52126951/72998239-3188db80-3e06-11ea-84be-4b69654216ad.png)
![image](https://user-images.githubusercontent.com/52126951/72998273-3e0d3400-3e06-11ea-83fa-351f574276cf.png)
![image](https://user-images.githubusercontent.com/52126951/72998292-46fe0580-3e06-11ea-8097-1c7f67f0060e.png)
![image](https://user-images.githubusercontent.com/52126951/72998309-4d8c7d00-3e06-11ea-88ad-6ecdedf91b46.png)

**Comment by hb3p8** [comment]
Moved to discord
