### ISSUE TITLE
LightTracer release notes

### ISSUE THREAD

**Issue by hb3p8** [light-tracer/issues#8]

**Comment by denisbogol** [comment]
We’re excited to announce the release of Light Tracer Render 1.2.0 – GPU-based ray tracer for desktop Web browsers (https://lighttracer.org). Find out what’s new in the quick facts below:

**Improved performance**

The new version delivers twice the performance in the interactive rendering during scene editing or camera manipulation. Optimized construction of accelerating structure results in a 30–40% decrease in scene initialization time.

**Better rendering controls**

Now you may set the maximum number of samples per pixel (SPP) before the rendering process stops. The higher the number of samples per pixel, the cleaner the final rendered image. The progress bar at the top of the window shows how much samples are already accumulated.

Rendering can be paused/resumed at any time. The paused mode uses just 4 SPP and thus can be used for scene editing with minimal GPU usage.

**Improved autofocus and depth-of-field**

By default, thin-lens camera parameters are adjusted automatically to achieve a nice-looking depth-of-field (DOF) effect. If autofocus with a central area is disabled, you may set focus to a particular object by clicking on it.

**Shadow catcher material**

Light Tracer allows to seamlessly blend your model with the environment map. Just use new shadow catcher material that takes its color from the environment behind it. All scene objects will cast shadows onto the shadow catcher.

**Verified unbiased rendering engine**

Rendering correctness was verified by comparison with comprehensive physically-based renderers such as PBRT and Mitsuba.

There are also other nice features in version 1.2.0, such as improved real-time denoising, HDR tone mapping and glow effect, ability to embed Light Tracer logo into the render, and, of course, fixes for the reported issues!

**Comment by ArixCuirax** [comment]
Awesome improvements in the new version, and very much appreciated! And requested features have been added as well, such as the ability to toggle a watermark.

I just have one question though. Does the rendering end once the 4000 samples per pixel threshold is reached?

Or do only the last 4000 samples count towards the computed colour of each pixel? Is it possible to continue having the quality of the render improve by simply allowing the render to continue for longer?

I'm used to leaving renders going over night for the best image quality possible without denoising and I'm hoping I can continue to do that and not have the render quality plateau after it reaches 4000 samples per pixel and not continue to improve further afterwards.

**Comment by hb3p8** [comment]
@ArixCuirax Thanks for your feedback!

`I just have one question though. Does the rendering end once the 4000 samples per pixel threshold is reached?`
That is correct, rendering stops after target sample count is reached.

Actually you could edit any field directly with `Ctrl + click` on slider. This way you could directly enter any desired value of target samples per pixel.

**Comment by ArixCuirax** [comment]
Can the maximum SPP threshhold please be increased to 50k? :)

**Comment by hb3p8** [comment]
Moved to discord
